hero_image: assets/img/sparklers.jpg
hero_position: center center
mobile_hero_image: assets/img/sparklers.jpg
mobile_hero_position: center center


    # Blue: #096da0
    # Off-white: #fbfdf8
    # Orange: #ea6e31
    # Dark green: #11382c
    # Moss green: #869b4c
    # Gold: #c4a142

theme:
 # text_color: '#096da0'
  primary_color: '#096da0'
  secondary_color: '#c4a142'
  #accent_color: '#afa63d'
  background_color: '#fbfdf8'
  